#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# First check if a location is set and is a valid swap partition
if [ -n "$RESUME" ] && [ "$RESUME" != auto ] && \
   { [ "$RESUME" = none ] || blkid -p -n swap $RESUME >/dev/null 2>&1; }; then
	# As mkinitramfs copies the config file nothing to do.
	exit 0
fi

# We need to be able to read the listed swap partitions
if ischroot || [ ! -r /proc/swaps ]; then
	resume_auto=
else
	# Try to autodetect the RESUME partition, using biggest swap?
	resume_auto=$(grep ^/dev/ /proc/swaps | sort -rnk3 | head -n 1 | cut -d " " -f 1)
	if [ -n "$resume_auto" ]; then
		UUID=$(blkid -s UUID -o value "$resume_auto" || true)
		if [ -n "$UUID" ]; then
			resume_auto="UUID=$UUID"
		fi
	fi
fi

# Write selected resume device to intramfs conf.d
if [ "$RESUME" = auto ] || [ -n "$resume_auto" ]; then
	echo "RESUME=${resume_auto}" > ${DESTDIR}/conf/conf.d/zz-resume-auto
fi
