#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# First check if a location is set and is a valid swap partition
if [ -n "$RESUME" ] && \
   { [ "$RESUME" = none ] || blkid -p -n swap $RESUME >/dev/null 2>&1; }; then
	# As mkinitramfs copies the config file nothing to do.
	exit 0
fi

# We need to be able to read the listed swap partitions
if ischroot || [ ! -r /proc/swaps ]; then
	exit 0
fi

# Try to autodetect the RESUME partition, using biggest swap?
# Write detected resume to intramfs conf.d
RESUME=$(grep ^/dev/ /proc/swaps | sort -rnk3 | head -n 1 | cut -d " " -f 1)
if [ -n "$RESUME" ]; then
	UUID=$(blkid -s UUID -o value "$RESUME" || true)
	if [ -n "$UUID" ]; then
			RESUME="UUID=$UUID"
	fi
	echo "RESUME=${RESUME}" > ${DESTDIR}/conf/conf.d/zz-resume-auto
fi
